# Generated by Django 5.2.17 on 2026-09-29 19:22

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTOR', 'Directeur / Responsable'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Élève'), ('PARENT', 'Parent / Tuteur'), ('ACCOUNTANT', 'Comptable / Caissier')], default='STUDENT', help_text="Rôle déterminant les permissions dans l'application", max_length=20, verbose_name='rôle')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='téléphone')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='photo de profil')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver au lieu de supprimer (RG19)', verbose_name='actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx')],
            },
        ),
    ]
